# Generated by Django 5.1.5 on 2025-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="traffic_flow_negatives",
            new_name="traffic_planning_negatives",
        ),
        migrations.RenameField(
            model_name="log",
            old_name="traffic_flow_positives",
            new_name="traffic_planning_positives",
        ),
        migrations.RemoveField(
            model_name="log",
            name="traffic_flow",
        ),
        migrations.AddField(
            model_name="log",
            name="efficiency",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="log",
            name="efficiency_negatives",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="efficiency_positives",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="problem_recognition",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="log",
            name="problem_recognition_negatives",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="problem_recognition_positives",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="reaction",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="log",
            name="reaction_negatives",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="reaction_positives",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="traffic_planning",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="log",
            name="ability_to_work_under_pressure",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="coordination",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="motivation",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="phraseology",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="separation",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="situational_awareness",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="tag_management",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="theory",
            field=models.IntegerField(
                choices=[
                    (0, "Not rated"),
                    (1, "Requirements not met"),
                    (2, "Requirements partially met"),
                    (3, "Requirements met"),
                    (4, "Requirements exceeded"),
                ]
            ),
        ),
    ]
