# Generated by Django 5.2 on 2025-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "logs",
            "0002_rename_traffic_flow_negatives_log_traffic_planning_negatives_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="next_step",
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
    ]
