# Generated by Django 5.2 on 2025-05-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_alter_log_next_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="type",
            field=models.TextField(
                choices=[("O", "Online"), ("S", "Sim"), ("L", "Lesson")], max_length=1
            ),
        ),
    ]
