# Generated by Django 5.2 on 2025-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0004_alter_log_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="next_step",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
