# Generated by Django 5.2.1 on 2025-05-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0005_alter_log_next_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="position",
            field=models.CharField(max_length=25),
        ),
    ]
