# Generated by Django 5.2.1 on 2025-07-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0007_alter_log_next_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="airspace_restrictions",
            field=models.TextField(
                blank=True,
                help_text="Any active NOTAMs, restrictions, or special airspace configurations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="runway_configuration",
            field=models.CharField(
                blank=True,
                help_text="e.g. 25L/07R, RNP X, etc.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="session_duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Session duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="special_procedures",
            field=models.TextField(
                blank=True,
                help_text="Any special procedures, events, or circumstances during the session",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="surrounding_stations",
            field=models.TextField(
                blank=True,
                help_text="List of active surrounding positions during the session",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="weather_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAVOK", "CAVOK"),
                    ("VMC", "VMC"),
                    ("IMC", "IMC"),
                    ("MARG", "Marginal"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
