# Generated by Django 5.2.1 on 2025-07-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0008_log_airspace_restrictions_log_runway_configuration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="traffic_complexity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Simple"),
                    ("M", "Moderate"),
                    ("C", "Complex"),
                    ("VC", "Very Complex"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="traffic_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VL", "Very Low"),
                    ("L", "Low"),
                    ("M", "Medium"),
                    ("H", "High"),
                    ("VH", "Very High"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="runway_configuration",
            field=models.CharField(
                blank=True,
                help_text="e.g. 25L/25R, RNP X, etc.",
                max_length=50,
                null=True,
            ),
        ),
    ]
