# Generated by Django 5.2.1 on 2025-07-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0010_alter_log_weather_conditions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="weather_conditions",
        ),
        migrations.AlterField(
            model_name="log",
            name="traffic_complexity",
            field=models.CharField(
                blank=True,
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="traffic_level",
            field=models.CharField(
                blank=True,
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                max_length=2,
                null=True,
            ),
        ),
    ]
