# Generated by Django 5.2 on 2025-05-29 19:09

import cpt.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lists", "0008_waitinglistentry_remarks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExaminerPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("TWR", "Tower"),
                            ("APP", "Approach"),
                            ("CTR", "Centre"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=cpt.models.default_8pm_today)),
                ("passed", models.BooleanField(blank=True, default=None, null=True)),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cpts",
                        to="lists.course",
                    ),
                ),
                (
                    "examiner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="examined_cpts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="local_cpts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Examiner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("callsign", models.CharField(max_length=10, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examiner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "positions",
                    models.ManyToManyField(
                        related_name="examiners", to="cpt.examinerposition"
                    ),
                ),
            ],
        ),
    ]
