# Generated by Django 5.2 on 2025-05-31 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpt", "0002_cpt_log_uploaded_cptlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="cptlog",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
