version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - automated

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - automated
    groups:
      laravel:
        patterns:
          - "laravel/*"
      filament:
        patterns:
          - "filament/*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - automated
    groups:
      radix:
        patterns:
          - "@radix-ui/*"
      tiptap:
        patterns:
          - "@tiptap/*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - automated
