# Generated by Django 5.2 on 2025-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endorsements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tier2Endorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("position", models.CharField(max_length=15)),
                ("moodle_course_id", models.IntegerField()),
            ],
        ),
    ]
