# Generated by Django 5.2 on 2025-06-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="last_rating_change",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
