# Generated by Django 5.2 on 2025-04-07 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rosterentry",
            name="removal_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="rosterentry",
            name="last_session",
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
