# Generated by Django 5.1.5 on 2025-03-22 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("endorsements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("airport_name", models.CharField(max_length=100)),
                ("airport_icao", models.CharField(max_length=4)),
                (
                    "solo_station",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "min_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Obs"),
                            (2, "S1"),
                            (3, "S2"),
                            (4, "S3"),
                            (5, "C1"),
                            (6, "C2"),
                            (7, "C3"),
                            (8, "I1"),
                            (9, "I2"),
                            (10, "I3"),
                            (1000, "Unl"),
                        ]
                    ),
                ),
                (
                    "max_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Obs"),
                            (2, "S1"),
                            (3, "S2"),
                            (4, "S3"),
                            (5, "C1"),
                            (6, "C2"),
                            (7, "C3"),
                            (8, "I1"),
                            (9, "I2"),
                            (10, "I3"),
                            (1000, "Unl"),
                        ]
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EDMT", "Endorsement"),
                            ("RTG", "Rating"),
                            ("GST", "Guest"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GND", "Ground"),
                            ("TWR", "Tower"),
                            ("APP", "Approach"),
                            ("CTR", "Centre"),
                        ],
                        max_length=3,
                    ),
                ),
                ("moodle_course_ids", models.JSONField(blank=True, default=list)),
                (
                    "active_trainees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="active_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "endorsement_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="courses",
                        to="endorsements.endorsementgroup",
                    ),
                ),
                (
                    "mentor_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                    ),
                ),
                (
                    "mentors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mentored_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaitingListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("activity", models.FloatField(default=0)),
                ("hours_updated", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lists.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
