# Generated by Django 5.1.5 on 2025-03-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("EDMT", "Endorsement"),
                    ("RTG", "Rating"),
                    ("GST", "Visitor"),
                ],
                max_length=4,
            ),
        ),
    ]
