# Generated by Django 5.2 on 2025-04-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_alter_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("EDMT", "Endorsement"),
                    ("RTG", "Rating"),
                    ("GST", "Visitor"),
                    ("FAM", "Familiarisation"),
                ],
                max_length=4,
            ),
        ),
    ]
