# Generated by Django 5.2 on 2025-04-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("familiarisations", "0001_initial"),
        ("lists", "0003_alter_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="familiarisation_sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="familiarisations.familiarisationsector",
            ),
        ),
    ]
