# Generated by Django 5.2 on 2025-05-01 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_course_familiarisation_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitinglistentry",
            name="hours_updated",
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
