# Generated by Django 5.2 on 2025-05-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_alter_waitinglistentry_hours_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("EDMT", "Endorsement"),
                    ("RTG", "Rating"),
                    ("GST", "Visitor"),
                    ("FAM", "Familiarisation"),
                    ("RST", "Roster Reentry"),
                ],
                max_length=4,
            ),
        ),
    ]
