# Generated by Django 5.2 on 2025-05-07 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0006_alter_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitinglistentry",
            name="date_added",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
