# Generated by Django 5.2 on 2025-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0007_alter_waitinglistentry_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglistentry",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
