# Generated by Django 5.2 on 2025-04-18 15:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("familiarisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="familiarisation",
            unique_together={("user", "sector")},
        ),
    ]
